version: '3'

services:
  kafka:
    build:
      context: ./docker
      dockerfile: Dockerfile.kafka
    container_name: kafka
    ports:
      - "2181:2181"
      - "9092:9092"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    ports:
      - "5601:5601"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/docker/docker_files/prometheus.yml:/etc/prometheus/prometheus.yml
  prometheus_pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - "9091:9091"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"