{
 "title": "TwitterProducer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Message Send duration (sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(messages_latency_seconds_sum[5m]) / rate(messages_latency_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Average Message Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Total Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "messages_total" }
   ]
  }
 ]
}